function copy_files_from_supercomputer(supercomputer,data_folder,domain_folder,filename)
hostname = ['mgibb@' supercomputer '.oerc.ox.ac.uk'];
remote_folder = [hostname ':~/CARP/fibres/data/' filename domain_folder '/'];

command = ['!scp ' remote_folder 'image_renum_i.elem ' ...
                   remote_folder 'image_renum_i.pts ' ...
                   remote_folder 'image_renum_i.tris ' ...
                   remote_folder 'vm.igb.gz ' ...
                   data_folder];

disp(command)
eval(command)
