function run_CARP(data_folder,params_file,domain_folder)

eval(['!' Config.CARP_executable ...
      ' +F ' Config.root_folder 'config/' params_file ...
      ' -meshname ' data_folder '/image_renum ' ...
      '-simID ' data_folder domain_folder]);