function run_CARP(pathstr,CARP_folder,params_file,domain_folder)

eval(['!' CARP_folder 'carp.mac ' ...
      '+F ' CARP_folder params_file ...
      ' -meshname ' pathstr '/image_renum ' ...
      '-simID ' pathstr domain_folder]);