function open_control_panel(setter)
% A figure containing various parameter controls

    % set function handles
    hplot_isosurface = @(source,eventdata)plot_isosurface(setter,source,eventdata);
    hslider_callback = @(source,eventdata)slider_Callback(setter,source,eventdata);
    % makes figure
    setter.hcontrol_panel = figure('MenuBar','none',...
        'Position',[0 0 500 500],...
        'Resize','off',...
        'Toolbar','none');
    
    % sets 'Arrows' button group and children
	setter.harrows = uibuttongroup('Title','Arrows',...
    	'Units','Pixels',...
        'Position',[10 10 140 130],...
        'SelectionChangeFcn',hplot_isosurface);
            
	setter.hnormals = uicontrol('Style','radiobutton',...
        'Parent',setter.harrows,...
        'Position',[10 100 120 20],...
        'String','grad V');
                        
	setter.hprojected = uicontrol('Style','radiobutton',...
        'Parent',setter.harrows,...
        'Position',[10 70 120 20],...
        'String','projected vector');
	
	setter.hfibre = uicontrol('Style','radiobutton',...
        'Parent',setter.harrows,...
        'Position',[10 40 120 20],...
        'String','fibre direction');

	setter.hnone = uicontrol('Style','radiobutton',...
        'Parent',setter.harrows,...
        'Position',[10 10 120 20],...
        'String','none');
    
    % sets 'Render' panel and children
	setter.hrender = uibuttongroup('Title','Render',...
        'Units','Pixels',...
        'Position',[160 10 140 70],...
        'SelectionChangeFcn',hplot_isosurface);

    setter.hvessel = uicontrol('Style','checkbox',...
        'Parent',setter.hrender,...
        'Position',[10 40 120 20],...
        'Callback',hplot_isosurface,...
        'String','vessel');
                        
	setter.hisosurface = uicontrol('Style','checkbox',...
        'Parent',setter.hrender,...
        'Position',[10 10 120 20],...
        'Callback',hplot_isosurface,...
        'String','sheet');
    
	% sets arrow size, potential slider and potential display
	setter.harrowsize = uicontrol('Style','edit',...
        'Position',[300 160 50 30],...
        'Callback',hplot_isosurface,...
        'String','1');

    setter.hslider = uicontrol('Style','slider',...
        'Position',[10 160 290 20],...
        'Callback',hslider_callback,...
        'Min',setter.tissue_block.min_V,...
        'Max',setter.tissue_block.max_V-1,...
        'Value',setter.tissue_block.min_V,...
        'SliderStep',[0.01 0.1]);

	setter.hV = uicontrol('Style','text',...
        'Position',[410 10 80 20],...
        'String',['V = ' num2str(get(setter.hslider,'Value'))]);
        
    	% sets the selected radio button to 'none'
        set(setter.harrows,'SelectedObject',setter.hnone);
        
end

function slider_Callback(setter,source,eventdata)
	set(setter.hV,'String',['V = ' num2str(get(setter.hslider,'Value'))])
	plot_isosurface(setter,source,eventdata)
end
